version: '3'

services:
  prover:
    image: hduoc2003/email-wallet-prover
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_USER=emailwallet
      - POSTGRES_DB=emailwallet
    ports:
      - "5432:5432"
    volumes:
      - "./mount-data:/var/lib/postgresql/data"
  # relayer:
  #   image: email-wallet-relayer
  #   build:
  #     context: ./email-wallet
  #     dockerfile: Relayer.Dockerfile
  #     # args:
  #     #   - modal_token_id=ak-QwCMvdQy97wHJqZYnOr2uD
  #     #   - modal_token_secret=as-qo3gD7gcWqC7cXWXtM5QQB

  #   entrypoint: /bin/sh
  #   command: -c "sleep 10000000"
  #   # network_mode: host
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - "./email-wallet/packages/relayer/.env:/email-wallet/packages/relayer/.env"
  #     - "./email-wallet/packages/subgraph/subgraph.yaml:/email-wallet/packages/subgraph/subgraph.yaml"
  #     # - "./email-wallet:/email-wallet"
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - prover
  #     - db
